version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute Pipeline (Build Source -> Test -> Build Web Server)
          command: |
            docker build -f integration.Dockerfile . -t local-weather-app:$CIRCLE_BRANCH
            mkdir -p docker-cache
            docker save local-weather-app:$CIRCLE_BRANCH | gzip > docker-cache/built-image.tar.gz
      - save_cache:
          key: build-image-{{ .BuildNum }}
          paths:
            - docker-cache
      - store_artifacts:
          path: docker-cache/build-image-tar.gz
          destination: build-image.tar.gz
    - run:
        name: Move compiled app to workspace
        command: |
          set -exu
          mkdir -p /tmp/workspace/dist
          mv dist/local-weather-app /tmp/workspace/dist/
    - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - dist/local-weather-app
  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npx now --token $NOW_TOKEN --platform-version 2 --prod /tmp/workspace/dist/local-weather-app --confirm

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
