version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute Pipeline (Build Source -> Test -> Build Web Server)
          command: |
            docker build -f integration.Dockerfile . -t localcast-weather:$CIRCLE_BRANCH
            mkdir -p docker-cache
            docker save localcast-weather:$CIRCLE_BRANCH | gzip > docker-cache/built-image.tar.gz

      - store_artifacts:
          path: docker-cache/build-image.tar.gz
          destination: built-image.tar.gz

      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace
            mv docker-cache/built-image.tar.gz /tmp/workspace/

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
